authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from pathlib import Path
from time import time

from django.contrib.auth.models import AbstractUser
from django.db import models

from mainapp.models import NULLABLE


def users_avatars_path(instance, filename):
    num = int(time() * 1000)
    suff = Path(filename).suffix
    return "user_{0}/avatars/{1}".format(instance.username, f"pic_{num}{suff}")


class User(AbstractUser):
    email = models.EmailField(blank=True, verbose_name='Email', unique=True)
    age = models.PositiveSmallIntegerField(verbose_name='Возраст', **NULLABLE)
    avatar = models.ImageField(upload_to=users_avatars_path, **NULLABLE)

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

authapp/forms.py
import os

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'age',
            'avatar',
        )

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError('Вы слишком молоды для этого сайта')
        return age


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'age',
            'avatar',
        )

    def clean_avatar(self):
        arg_as_str = "avatar"
        if arg_as_str in self.changed_data and self.instance.avatar:
            if os.path.exists(self.instance.avatar.path):
                os.remove(self.instance.avatar.path)
        return self.cleaned_data.get(arg_as_str)

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise ValidationError('Вы слишком молоды для этого сайта')
        return age

authapp/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, UpdateView

from authapp.forms import CustomUserCreationForm, CustomUserChangeForm
from authapp.models import User


# Create your views here.
class CustomLoginView(LoginView):
    template_name = 'authapp/login.html'
    extra_context = {
        'title': 'Вход пользователя'
    }

    def form_valid(self, form):
        ret = super().form_valid(form)

        message = _("Login success!<br>Hi, %(username)s") % {
            "username": self.request.user.get_full_name()
            if self.request.user.get_full_name()
            else self.request.user.get_username()
        }
        messages.add_message(self.request, messages.INFO, mark_safe(message))
        return ret

    def form_invalid(self, form):
        for _unused, msg in form.error_messages.items():
            messages.add_message(
                self.request,
                messages.WARNING,
                mark_safe(f"Something goes wrong:<br>{msg}"),
            )
        return self.render_to_response(self.get_context_data(form=form))


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.INFO, _("See you later!"))
        return super().dispatch(request, *args, **kwargs)


class RegisterView(CreateView):
    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('mainapp:index')


class EditView(UpdateView):
    model = User
    form_class = CustomUserChangeForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        print(self.request.user.pk)
        return reverse_lazy('authapp:edit')

authapp/templates/authapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to GeekLab!</title>
</head>

<body>

{% block messages %}
{% include 'authapp/includes/inc_messages.html' %}
{% endblock messages %}

<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0">
    <div class="text-center">
        <p>
            <a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
        </p>
        <h2>{{ title }}</h2>

        {% block content %}
        {% endblock %}

        <p>
        <h4>Вход через социальные сети</h4>
        </p>
        <div class="btn-group btn-block" role="group">
            <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
            <a class="btn btn-primary" href="{% url 'social:begin' 'github' %}" role="button"><i class="fab fa-github"></i></a>
            <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
        </div>
        </p>
    </div>
</div>


<!-- JavaScript section -->
<!-- Bootstrap -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- ChartJs -->
<script src="{% static 'js/Chart.min.js' %}"></script>

<!-- FontAwesome -->
<script src="{% static 'js/fontawesome.all.min.js' %}"></script>


{% block js %}

{% endblock %}

</body>

</html>

authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <form class="col-6 m-auto pt-5 pb-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <p>
            <button type="submit" class="btn btn-primary btn-block">
                Сохранить
            </button>
        </p>
    </form>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        <p>
            <input id="id_username"
                   class="form-control"
                   type="text"
                   name="username"
                   placeholder="Имя пользователя"
                   required=""
                   autofocus="">
        </p>
        <p>
            <input id="id_password"
                   class="form-control"
                   type="password"
                   name="password"
                   placeholder="Пароль"
                   required="">
        </p>
        <p>
            <button type="submit" class="btn btn-primary btn-block">Войти</button>
        </p>
    </form>
    <div class="row justify-content-between">
        <div class="col">
            <a href="{% url 'authapp:register' %}"><small>Регистрация</small></a>
        </div>
        <div class="col">
            <a href="#"><small>Забыли пароль?</small></a>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/user_form.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="row justify-content-center my-2">
        <div class="col-lg-6">
            {% if user.is_anonymous %}
                <h3>Регистрация нового пользователя</h3>
            {% else %}
                <h3>Редактировать профиль</h3>
                <div class="row justify-content-center">
                    <div class="col-sm-7 col-md-5 col-lg-4">
                        {% if user.avatar %}
                            <img src="{{ user.avatar.url }}" alt="" width="100%">
                        {% else %}
                            <img src="{{ MEDIA_URL }}avatar_default.svg" alt="" width="100%">
                        {% endif %}
                    </div>
                </div>
            {% endif %}
            <form method="post" class="mt-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">
                    {% if user.is_anonymous %}
                        Зарегистрироваться
                    {% else %}
                        Сохранить
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if messages %}
                // Toasts
                $(".toast").toast({delay: 5000});
                $(".toast").toast("show");
            {% endif %}
        });
    </script>
{% endblock %}