authapp/urls.py
from authapp.apps import AuthappConfig
from django.urls import path
from authapp.views import CustomLoginView, RegisterView, CustomLogoutView, EditView

app_name = AuthappConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('edit/', EditView.as_view(), name='edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp import views
from mainapp.apps import MainappConfig


app_name = MainappConfig.name

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('doc_site/', views.DocSiteView.as_view(), name='doc_site'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('search/', views.google_redirect_view, name='search'),

    # Courses
    path('courses_list/', cache_page(300)(views.CoursesListView.as_view()), name='courses_list'),
    path('courses/<int:pk>/detail/', views.CourseDetailView.as_view(), name='courses_detail'),
    path('courses/feedback/', views.CourseFeedbackCreateView.as_view(), name='course_feedback'),

    # News
    path('news/', views.NewsListView.as_view(), name='news'),
    path('news/add/', views.NewsCreateView.as_view(), name='news_create'),
    path('news/<int:pk>/update/', views.NewsUpdateView.as_view(), name='news_update'),
    path('news/<int:pk>/detail/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news_delete'),

    # Logs
    path('logs/', views.LogView.as_view(), name='log_list'),
    path('logs/download', views.LogDownloadView.as_view(), name='log_download'),
]

mainapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from config import settings

NULLABLE = {'blank': True, 'null': True}


class CommonModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')
    deleted = models.BooleanField(default=False, verbose_name='Удалено')

    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()


class News(CommonModel):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    preamble = models.CharField(max_length=1024, verbose_name='Вступление')

    body = models.TextField(verbose_name='Содержимое')
    body_as_markdown = models.BooleanField(default=False, verbose_name='Разметка Markdown')

    def __str__(self):
        return f'{self.pk} {self.title}'

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")


class Course(CommonModel):
    name = models.CharField(max_length=256, verbose_name='Название')
    description = models.CharField(max_length=1024, verbose_name='Описание')

    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Стоимость', default=0)
    cover = models.CharField(max_length=25, default='img/no_image.svg', verbose_name='Cover')
    description_as_markdown = models.BooleanField(default=False, verbose_name='Разметка Markdown')

    def __str__(self):
        return f'{self.pk} {self.name}'

    class Meta:
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")


class Lesson(CommonModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Курс')
    num = models.PositiveIntegerField(default=0, verbose_name='Номер урока')

    title = models.CharField(max_length=256, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание')
    description_as_markdown = models.BooleanField(default=False, verbose_name='Разметка Markdown')

    def __str__(self):
        return f'#{self.num} {self.title}'

    class Meta:
        verbose_name = _("Lesson")
        verbose_name_plural = _("Lessons")


class CourseTeacher(CommonModel):
    course = models.ManyToManyField(Course)
    first_name = models.CharField(max_length=256, verbose_name='Имя')
    last_name = models.CharField(max_length=256, verbose_name='Фамилия')

    def __str__(self):
        return '{0:0>3} {1} {2}'.format(self.pk, self.last_name, self.first_name)

    class Meta:
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")


class CourseFeedback(CommonModel):
    RATING_FIVE = 5

    RATINGS = (
        (RATING_FIVE, '⭐⭐⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (3, '⭐⭐⭐'),
        (2, '⭐⭐'),
        (1, '⭐'),
    )

    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=_('Course'))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('User'))
    rating = models.SmallIntegerField(choices=RATINGS, default=RATING_FIVE, verbose_name=_('Rating'))
    feedback = models.TextField(verbose_name=_('Feedback'), default=_('No feedback'))

    class Meta:
        verbose_name = _('Feedback')
        verbose_name_plural = _('Feedbacks')

    def __str__(self):
        return f'Отзыв на {self.course} от {self.user}'

mainapp/forms.py
from django import forms

from mainapp.models import CourseFeedback


class CourseFeedBackForm(forms.ModelForm):

    class Meta:
        model = CourseFeedback
        fields = ('course', 'user', 'rating', 'feedback',)
        widgets = {
            'course': forms.HiddenInput(),
            'user': forms.HiddenInput(),
            'rating': forms.RadioSelect(),
        }

    def __init__(self, *args, course=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if course and user:
            self.fields['course'].initial = course.pk
            self.fields['user'].initial = user.pk

mainapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.http import HttpResponseRedirect, JsonResponse, Http404, FileResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DetailView, DeleteView, View

from config import settings
from mainapp import tasks
from mainapp.forms import CourseFeedBackForm
from mainapp.models import News, Course, Lesson, CourseTeacher, CourseFeedback


class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def post(self, *args, **kwargs):
        message_body = self.request.POST.get('message_body')
        message_from = self.request.user.pk if self.request.user.is_authenticated else None
        tasks.send_feedback_to_email.delay(message_body, message_from)

        return HttpResponseRedirect(reverse_lazy('mainapp:contacts'))


class CoursesListView(ListView):
    template_name = 'mainapp/courses_list.html'
    model = Course
    paginate_by = 6


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsListView(ListView):
    model = News
    paginate_by = 4

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class NewsDetailView(DetailView):
    model = News

    def get_object(self, queryset=None):
        if super().get_object().deleted is True:
            raise Http404
        return super().get_object()


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.add_news',)


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.change_news',)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = News
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.delete_news',)


class CourseDetailView(TemplateView):
    template_name = 'mainapp/courses_detail.html'

    def get_context_data(self, pk=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['course_object'] = get_object_or_404(Course, pk=self.kwargs.get('pk'))
        context_data['lessons'] = Lesson.objects.filter(course=context_data['course_object'])
        context_data['teachers'] = CourseTeacher.objects.filter(course=context_data['course_object'])

        feedback_list_key = f'course_feedback_{context_data["course_object"].pk}'
        cached_feedback_list = cache.get(feedback_list_key)
        if cached_feedback_list is None:
            context_data['feedback_list'] = CourseFeedback.objects.filter(course=context_data['course_object'])
            cache.set(feedback_list_key, context_data['feedback_list'], timeout=300)
        else:
            context_data['feedback_list'] = cached_feedback_list

        user = self.request.user
        feedback_list = context_data['feedback_list']

        if user.is_authenticated:
            if feedback_list:
                for feedback in feedback_list:
                    if feedback.user.pk == self.request.user.pk:
                        return context_data

            context_data['feedback_form'] = CourseFeedBackForm(
                course=context_data['course_object'],
                user=self.request.user
            )

        cached_feedback = cache.get(f"feedback_list_{pk}")
        if not cached_feedback:
            context_data["feedback_list"] = (
                CourseFeedback.objects.filter(course=context_data["course_object"])
                .select_related()
            )
            cache.set(f"feedback_list_{pk}", context_data["feedback_list"], timeout=300)

            # Archive object for tests --->
            import pickle

            with open(f"mainapp/fixtures/005_feedback_list_{pk}.bin", "wb") as out_file:
                pickle.dump(context_data["feedback_list"], out_file)
            # <--- Archive object for tests

        else:
            context_data["feedback_list"] = cached_feedback

        return context_data


class CourseFeedbackCreateView(CreateView):
    model = CourseFeedback
    form_class = CourseFeedBackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_template = render_to_string('mainapp/incldues/feedback_card.html', context={'item': self.object})
        return JsonResponse({'card': rendered_template})


class LogView(UserPassesTestMixin, TemplateView):
    template_name = 'mainapp/logs.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        log_lines = []
        with open(settings.LOG_FILE, 'r') as log_file:
            for i, line in enumerate(log_file):
                if i == 1000:
                    break
                log_lines.insert(0, line)

            context_data['logs'] = log_lines
        print(len(context_data['logs']))
        return context_data


class LogDownloadView(UserPassesTestMixin, View):

    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, 'rb'))


def google_redirect_view(request):
    search_string = request.GET.get('search_string')
    return HttpResponseRedirect(f'https://www.google.com/search?q={search_string}')

mainapp/templates/mainapp/incldues/feedback_card.html
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ item.get_rating_display }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ item.user }}</h6>
        <p class="card-text">
            {{ item.feedback }}
        </p>
    </div>
</div>

mainapp/templates/mainapp/incldues/main_menu.html
{% load static i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:index' %}">
            <img src="{% static 'img/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                    <a class="nav-link {% if request.resolver_match.view_name == 'mainapp:news' %}active{% endif %}"
                       href="{% url 'mainapp:news' %}">
                        {% translate "News" %}
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link {% if request.resolver_match.view_name == 'mainapp:courses_list' %}active{% endif %}"
                       href="{% url 'mainapp:courses_list' %}">
                        {% translate "Courses" %}
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            {% translate "Profile" %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="ddProfile">
                            <span class="dropdown-item disabled">{{ user.username }}</span>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'authapp:edit' %}">{% translate "Edit profile" %}</a>
                            <a class="dropdown-item" href="#">{% translate 'My courses' %}</a>
                            {% if user.is_staff %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'admin:index' %}">{% translate 'Moderation' %}</a>
                            {% endif %}
                            {% if user.is_superuser %}
                                <a class="dropdown-item"
                                   href="{% url 'admin:index' %}">{% translate 'Administrative section' %}</a>
                                <a class="dropdown-item" href="{% url 'mainapp:log_list' %}">{% translate 'Logs' %}</a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'authapp:logout' %}">{% translate 'Logout' %}</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'authapp:login' %}">{% translate 'Login' %}</a>
                    </li>
                {% endif %}
                <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:contacts' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:contacts' %}">{% translate 'Contacts' %}</a>
                </li>
            </ul>

            <div class="row justify-content-end m-0">
                <div class="col p-0 border-right">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="language" type="hidden" value="ru">
                        <button type="submit" class="btn btn-link">🇷🇺</button>
                    </form>
                </div>
                <div class="col p-0">
                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="language" type="hidden" value="en">
                        <button type="submit" class="btn btn-link">🇬🇧</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</nav>