config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace='mainapp')),
    path('authapp/', include('authapp.urls', namespace='authapp')),
    path('social_auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mainapp import views
from mainapp.apps import MainappConfig


app_name = MainappConfig.name

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('doc_site/', views.DocSiteView.as_view(), name='doc_site'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('search/', views.google_redirect_view, name='search'),

    # Courses
    path('courses_list/', cache_page(300)(views.CoursesListView.as_view()), name='courses_list'),
    path('courses/<int:pk>/detail/', views.CourseDetailView.as_view(), name='courses_detail'),
    path('courses/feedback/', views.CourseFeedbackCreateView.as_view(), name='course_feedback'),

    # News
    path('news/', views.NewsListView.as_view(), name='news'),
    path('news/add/', views.NewsCreateView.as_view(), name='news_create'),
    path('news/<int:pk>/update/', views.NewsUpdateView.as_view(), name='news_update'),
    path('news/<int:pk>/detail/', views.NewsDetailView.as_view(), name='news_detail'),
    path('news/<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news_delete'),

    # Logs
    path('logs/', views.LogView.as_view(), name='log_list'),
    path('logs/download', views.LogDownloadView.as_view(), name='log_download'),
]

mainapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from config import settings

NULLABLE = {'blank': True, 'null': True}


class CommonModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Обновлен')
    deleted = models.BooleanField(default=False, verbose_name='Удалено')

    class Meta:
        abstract = True

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()


class News(CommonModel):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    preamble = models.CharField(max_length=1024, verbose_name='Вступление')

    body = models.TextField(verbose_name='Содержимое')
    body_as_markdown = models.BooleanField(default=False, verbose_name='Разметка Markdown')

    def __str__(self):
        return f'{self.pk} {self.title}'

    class Meta:
        verbose_name = _("News")
        verbose_name_plural = _("News")


class Course(CommonModel):
    name = models.CharField(max_length=256, verbose_name='Название')
    description = models.CharField(max_length=1024, verbose_name='Описание')

    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Стоимость', default=0)
    cover = models.CharField(max_length=25, default='img/no_image.svg', verbose_name='Cover')
    description_as_markdown = models.BooleanField(default=False, verbose_name='Разметка Markdown')

    def __str__(self):
        return f'{self.pk} {self.name}'

    class Meta:
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")


class Lesson(CommonModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Курс')
    num = models.PositiveIntegerField(default=0, verbose_name='Номер урока')

    title = models.CharField(max_length=256, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание')
    description_as_markdown = models.BooleanField(default=False, verbose_name='Разметка Markdown')

    def __str__(self):
        return f'#{self.num} {self.title}'

    class Meta:
        verbose_name = _("Lesson")
        verbose_name_plural = _("Lessons")


class CourseTeacher(CommonModel):
    course = models.ManyToManyField(Course)
    first_name = models.CharField(max_length=256, verbose_name='Имя')
    last_name = models.CharField(max_length=256, verbose_name='Фамилия')

    def __str__(self):
        return '{0:0>3} {1} {2}'.format(self.pk, self.last_name, self.first_name)

    class Meta:
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")


class CourseFeedback(CommonModel):
    RATING_FIVE = 5

    RATINGS = (
        (RATING_FIVE, '⭐⭐⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (3, '⭐⭐⭐'),
        (2, '⭐⭐'),
        (1, '⭐'),
    )

    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=_('Course'))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('User'))
    rating = models.SmallIntegerField(choices=RATINGS, default=RATING_FIVE, verbose_name=_('Rating'))
    feedback = models.TextField(verbose_name=_('Feedback'), default=_('No feedback'))

    class Meta:
        verbose_name = _('Feedback')
        verbose_name_plural = _('Feedbacks')

    def __str__(self):
        return f'Отзыв на {self.course} от {self.user}'

mainapp/forms.py
from django import forms

from mainapp.models import CourseFeedback


class CourseFeedBackForm(forms.ModelForm):

    class Meta:
        model = CourseFeedback
        fields = ('course', 'user', 'rating', 'feedback',)
        widgets = {
            'course': forms.HiddenInput(),
            'user': forms.HiddenInput(),
            'rating': forms.RadioSelect(),
        }

    def __init__(self, *args, course=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if course and user:
            self.fields['course'].initial = course.pk
            self.fields['user'].initial = user.pk

mainapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.http import HttpResponseRedirect, JsonResponse, Http404, FileResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DetailView, DeleteView, View

from config import settings
from mainapp import tasks
from mainapp.forms import CourseFeedBackForm
from mainapp.models import News, Course, Lesson, CourseTeacher, CourseFeedback


class ContactsView(TemplateView):
    template_name = 'mainapp/contacts.html'

    def post(self, *args, **kwargs):
        message_body = self.request.POST.get('message_body')
        message_from = self.request.user.pk if self.request.user.is_authenticated else None
        tasks.send_feedback_to_email.delay(message_body, message_from)

        return HttpResponseRedirect(reverse_lazy('mainapp:contacts'))


class CoursesListView(ListView):
    template_name = 'mainapp/courses_list.html'
    model = Course
    paginate_by = 6


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsListView(ListView):
    model = News
    paginate_by = 4

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class NewsDetailView(DetailView):
    model = News

    def get_object(self, queryset=None):
        if super().get_object().deleted is True:
            raise Http404
        return super().get_object()


class NewsCreateView(PermissionRequiredMixin, CreateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.add_news',)


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    model = News
    fields = '__all__'
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.change_news',)


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    model = News
    success_url = reverse_lazy('mainapp:news')
    permission_required = ('mainapp.delete_news',)


class CourseDetailView(TemplateView):
    template_name = 'mainapp/courses_detail.html'

    def get_context_data(self, pk=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['course_object'] = get_object_or_404(Course, pk=self.kwargs.get('pk'))
        context_data['lessons'] = Lesson.objects.filter(course=context_data['course_object'])
        context_data['teachers'] = CourseTeacher.objects.filter(course=context_data['course_object'])

        feedback_list_key = f'course_feedback_{context_data["course_object"].pk}'
        cached_feedback_list = cache.get(feedback_list_key)
        if cached_feedback_list is None:
            context_data['feedback_list'] = CourseFeedback.objects.filter(course=context_data['course_object'])
            cache.set(feedback_list_key, context_data['feedback_list'], timeout=300)
        else:
            context_data['feedback_list'] = cached_feedback_list

        user = self.request.user
        feedback_list = context_data['feedback_list']

        if user.is_authenticated:
            if feedback_list:
                for feedback in feedback_list:
                    if feedback.user.pk == self.request.user.pk:
                        return context_data

            context_data['feedback_form'] = CourseFeedBackForm(
                course=context_data['course_object'],
                user=self.request.user
            )

        cached_feedback = cache.get(f"feedback_list_{pk}")
        if not cached_feedback:
            context_data["feedback_list"] = (
                CourseFeedback.objects.filter(course=context_data["course_object"])
                .select_related()
            )
            cache.set(f"feedback_list_{pk}", context_data["feedback_list"], timeout=300)

            # Archive object for tests --->
            import pickle

            with open(f"mainapp/fixtures/005_feedback_list_{pk}.bin", "wb") as out_file:
                pickle.dump(context_data["feedback_list"], out_file)
            # <--- Archive object for tests

        else:
            context_data["feedback_list"] = cached_feedback

        return context_data


class CourseFeedbackCreateView(CreateView):
    model = CourseFeedback
    form_class = CourseFeedBackForm

    def form_valid(self, form):
        self.object = form.save()
        rendered_template = render_to_string('mainapp/incldues/feedback_card.html', context={'item': self.object})
        return JsonResponse({'card': rendered_template})


class LogView(UserPassesTestMixin, TemplateView):
    template_name = 'mainapp/logs.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        log_lines = []
        with open(settings.LOG_FILE, 'r') as log_file:
            for i, line in enumerate(log_file):
                if i == 1000:
                    break
                log_lines.insert(0, line)

            context_data['logs'] = log_lines
        print(len(context_data['logs']))
        return context_data


class LogDownloadView(UserPassesTestMixin, View):

    def test_func(self):
        return self.request.user.is_superuser

    def get(self, *args, **kwargs):
        return FileResponse(open(settings.LOG_FILE, 'rb'))


def google_redirect_view(request):
    search_string = request.GET.get('search_string')
    return HttpResponseRedirect(f'https://www.google.com/search?q={search_string}')

mainapp/templates/mainapp/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.all.min.css' %}">

    <title>Welcome to Braniac!</title>
</head>

<body>

{% include 'mainapp/incldues/main_menu.html' %}

<div class="container-md">

    {% block content %}
    {% endblock %}

</div>


<!-- Footer -->
<div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Braniac</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="{% url 'mainapp:index' %}">Домашняя</a></li>
                <li><a href="{% url 'mainapp:news' %}">Новости</a></li>
                <li><a href="{% url 'mainapp:login' %}">Войти</a></li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Полезное</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="#">Положения &amp; Условия</a></li>
                <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                <li><a href="#">Документация по API</a></li>
                <li><a href="{% url 'mainapp:doc_site' %}">Документация по сайту</a></li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Мы в социальных сетях</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
            </div>
            </p>
            <p>
                <strong>Наше приложение</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
            </div>
            </p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div>
            <p><small>&copy; GeekBrains 2021</small></p>
        </div>
    </div>
</div>
<!-- /Footer -->


<!-- JavaScript section -->
<!-- Bootstrap -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- ChartJs -->
<script src="{% static 'js/Chart.min.js' %}"></script>

<!-- FontAwesome -->
<script src="{% static 'js/fontawesome.all.min.js' %}"></script>

{% block js %}
{% endblock js %}

</body>
</html>

mainapp/templates/mainapp/courses_detail.html
{% extends 'mainapp/base.html' %}
{% load static markdownify crispy_forms_filters cache %}

{% block title %}
    {{ course_object.name }}
{% endblock title %}

{% block content %}
    <h1 class="mt-2">
        {{ course_object.name }}
    </h1>
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-6 col-lg-8 order-2 order-md-1">
            <div class="row h-100">
                <div class="col-12">
                    {% if course_object.description_as_markdown %}
                        {{ course_object.description|markdownify }}
                    {% else %}
                        {{ course_object.description }}
                    {% endif %}
                </div>
                <div class="col-12 align-self-end">
                    <p>
                        <small>Преподаватели</small><br>
                        {% for item in teachers %}
                            {{ item.last_name }} {{ item.first_name }}{% if forloop.last %}{% else %},{% endif %}
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-4 order-1 order-md-2">
            <div class="row h-100">
                <div class="col-12 align-self-start">
                    <img class="w-100" src="{% static course_object.cover %}" alt="">
                </div>
                <div class="col-12 align-self-end d-none d-md-block">
                    <p class="text-center mt-2">
                        <small class="text-uppercase">цена</small><br>
                        <span style="font-size: 30pt;">
            {{ course_object.cost }}
          </span><br>
                        <a href="#" class="btn btn-outline-primary btn-block"
                           role="button">Купить</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 d-md-none order-3 order-sm-3">
            <p class="text-center">
                <small class="text-uppercase">цена</small><br>
                <span style="font-size: 30pt;">
        {{ course_object.cost }}
      </span><br>
                <a href="#" class="btn btn-outline-primary btn-block"
                   role="button">Купить</a>
            </p>
        </div>
    </div>
    <div class="accordion" id="accordionLessons">

            {% for item in lessons %}
                <div class="card">
                    <div class="card-header" id="headLessonPk{{ item.pk }}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button"
                                    data-toggle="collapse" data-target="#collapse{{ item.pk }}"
                                    aria-expanded="true" aria-controls="collapse{{ item.pk }}">
                                {{ item.course.name }} - {{ item.title }}
                            </button>
                        </h2>
                    </div>

                    <div id="collapse{{ item.pk }}" class="collapse"
                         aria-labelledby="headLessonPk{{ item.pk }}"
                         data-parent="#accordionLessons">
                        <div class="card-body">
                            <div class="row justify-content-center">
                                <div class="col-12 text-center">
                                    <img src="{% static 'img/no_image.svg' %}" width="250px" alt="">
                                </div>
                                <div class="col-12">
                                    {% if item.description_as_markdown %}
                                        {{ item.description|markdownify }}
                                    {% else %}
                                        {{ item.description }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

    </div>
    <h3>Отзывы</h3>

    <div id="feedback_list">
        {% if feedback_list %}
            {% for item in feedback_list %}
                {% include 'mainapp/incldues/feedback_card.html' %}
            {% endfor %}
        {% else %}
            <p id="feedbackBeFirst">
                No feedback yet. Be first!
            </p>
        {% endif %}
    </div>

    {% if feedback_form %}
        <div class="card" id="cardForm">
            <div class="card-body">
                <h5 class="card-title">Добавить отзыв</h5>
                <h6 class="card-subtitle mb-2 text-muted">Вы ещё не оставляли отзыв к этому
                    курсу</h6>
                <p class="card-text">
                <form action="{% url 'mainapp:course_feedback' %}" method="POST"
                      id="feedbackForm">
                    {% csrf_token %}
                    {{ feedback_form|crispy }}
                </form>
                <button id="feedbackSubmit"
                        class="btn btn-primary btn-block">Отправить
                </button>
                </p>
            </div>
        </div>
    {% endif %}

{% endblock content %}

{% block js %}
    <script>
        $(document).ready(function () {
            {% if feedback_form %}
                $("#feedbackSubmit").click(function () {
                    $("#cardForm").hide();
                    let $form = $("#feedbackForm");
                    $.ajax({
                        type: "POST",
                        url: $form.attr("action"),
                        data: $form.serialize(),
                        success: function (data) {
                            $("#feedback_list").append(data.card);
                            $(".no-feedback").remove();
                        }
                    });
                });
            {% endif %}
        });
    </script>
{% endblock js %}

mainapp/templates/mainapp/courses_list.html
{% extends 'mainapp/base.html' %}
{% load static i18n %}

{% block title %}
    Курсы
{% endblock title %}

{% block content %}
    <div class="row justify-content-center mt-3">
        {% for item in object_list %}
            <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
                <a href="{% url 'mainapp:courses_detail' pk=item.pk %}">
                    <img src="{% static item.cover %}" class="card-img-top" alt="">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ item.name }}</h5>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    <div class="row justify-content-center align-items-center mt-3 mb-n3">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">
                        {% translate 'Previous' %}</a>
                    </li>
                {% endif %}

                {% for item in page_obj.paginator.page_range %}
                    <li class="page-item {% if item == page_obj.number %}active{% endif %}">
                        <a class="page-link" href="?page={{ item }}">{{ item }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.next_page_number }}">
                        {% translate 'Next' %}</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock content %}

mainapp/templates/mainapp/logs.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <p>
    <div class="card">
        <div class="card-header">
            Первые 1000 строк логов
            <div class="col-sm-4 col-lg-2 float-right">
                <a href="{% url 'mainapp:log_download' %}" class="btn btn-primary btn-block" role="button">Скачать логи
                </a>
            </div>
        </div>
        <div class="card-body overflow-auto" style="max-height: 50em">
            {% for log in logs %}
                {{ log }}<br>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

mainapp/templates/mainapp/news_confirm_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <div class="row justify-content-center pt-3">
        <div class="col-md-8 col-lg-6">
            <h2>Пометить новость удалённой?</h2>
            <p>
                Поставить отметку удаления для новости:<br>
                "{{ object.title }}" от {{ object.created }}
            </p>
            <p>
            <div class="row">
                <div class="col-6">
                    <form action="{% url 'mainapp:news_delete' pk=object.pk %}"
                          method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger btn-block"
                                type="submit">Подтвердить
                        </button>
                    </form>
                </div>
                <div class="col-6">
                    <a class="btn btn-primary btn-block" href="{% url 'mainapp:news' %}"
                       role="button">Отмена</a>
                </div>
            </div>
            </p>
        </div>
    </div>
{% endblock content %}

mainapp/templates/mainapp/news_detail.html
{% extends 'mainapp/base.html' %}

{% block title %}
    {{ object.title|default:"Новости" }}
{% endblock title %}
{% block content %}
    <div class="row justify-content-center pt-3">
        <div class="col-md-12 col-lg-8">
            <div class="card shadow">
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">
                        {{ object.body }}
                    </p>
                    <a href="{% url 'mainapp:news' %}" class="btn btn-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

mainapp/templates/mainapp/news_form.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="row justify-content-center pt-3">
        <div class="col-md-12 col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">
                    Опубликовать
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

mainapp/templates/mainapp/news_list.html
{% extends 'mainapp/base.html' %}
{% load i18n %}

{% block title %}
    Новости
{% endblock title %}
{% block content %}
    {% if page_num %}
        <div class="card my-2">
            <div class="card-body">
                <p class="card-text">Текущая страница: {{ page_num }}</p>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-lg-8">
            {% for item in object_list %}
                <div class="card my-2">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            {{ item.created|date:"Y-m-d h-i-s" }}
                        </h6>
                        <p class="card-text">{{ item.preambule }}</p>
                        <div class="row">
                            <div class="col">
                                <a href="{% url 'mainapp:news_detail' pk=item.pk %}"
                                   class="card-link">Подробнее</a>
                            </div>
                            {% if perms.mainapp.change_news %}
                                <div class="col-1 text-center">
                                    <a href="{% url 'mainapp:news_update' pk=item.pk %}">
                                        <i class="far fa-edit"></i>
                                    </a>
                                </div>
                            {% endif %}
                            {% if perms.mainapp.delete_news %}
                                <div class="col-1 text-center">
                                    <a href="{% url 'mainapp:news_delete' pk=item.pk %}">
                                        <i class="far fa-trash-alt"></i>
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-lg-4">
            <div class="card my-2 sticky-top">
                <div class="card-header">
                    Фильтры
                </div>
                <div class="card-body">
                    <form action="">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Дата от...</span>
                            </div>
                            <input type="date" class="form-control" name="dateFrom">
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">Дата до...</span>
                            </div>
                            <input type="date" class="form-control" name="dateTo">
                        </div>
                        <button type="submit"
                                class="btn btn-primary btn-block">Фильтровать
                        </button>
                    </form>
                </div>
            </div>
            {% if perms.mainapp.add_news %}
                <a class="btn btn-primary btn-block" role="button"
                   href="{% url 'mainapp:news_create' %}">Добавить новость</a>
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center align-items-center mt-3 mb-n3">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">
                        {% translate 'Previous' %}</a>
                    </li>
                {% endif %}

                {% for item in page_obj.paginator.page_range %}
                    <li class="page-item {% if item == page_obj.number %}active{% endif %}">
                        <a class="page-link" href="?page={{ item }}">{{ item }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.next_page_number }}">
                        {% translate 'Next' %}</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock content %}